# azure-pipelines.yml

trigger:
- main  # Trigger on commits to main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu build agent

stages:
- stage: Build
  displayName: "Packer Build Stage"
  jobs:
  - job: PackerBuild
    displayName: "Run Packer"
    steps:
    - checkout: self

    # Initialize Packer
    - script: packer init $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
      displayName: "Packer init"

    # Validate the Packer template
    - script: packer validate $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
      displayName: "Packer validate template"

    # Build the Packer template with Azure credentials
    - script: packer build $(Build.SourcesDirectory)/CHAP08/packer/.pkr.hcl
      displayName: "Packer build template"
      env:
        PKR_VAR_clientid: $(PKR_VAR_clientid)
        PKR_VAR_clientsecret: $(PKR_VAR_clientsecret)
        PKR_VAR_subscriptionid: $(PKR_VAR_subscriptionid)
        PKR_VAR_tenantid: $(PKR_VAR_tenantid)

